[package]
name = "dyn-cc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dyn-cc"
path = "src/main.rs"


[dependencies]
anyhow = "1.0.100"
indicatif = "0.18.2"
rand = "0.9.2"
raphtory = "0.16.3"
rayon = "1.11.0"
